export default keywords = [
      "sức khỏe",
      "sức khỏe tổng quát",
      "chế độ ăn uống lành mạnh",
      "tập luyện thể thao",
      "giảm cân",
      "tăng cân",
      "sức khỏe tinh thần",
      "stress và cách giảm stress",
      "ngủ ngon",
      "vitamin và khoáng chất",
      "bệnh tim mạch",
      "bệnh tiểu đường",
      "huyết áp",
      "cholesterol",
      "sức khỏe xương khớp",
      "sức khỏe phụ nữ",
      "sức khỏe nam giới",
      "sức khỏe trẻ em",
      "tiêm phòng",
      "bệnh ung thư",
      "dinh dưỡng",
      "detox cơ thể",
      "sức khỏe mắt",
      "sức khỏe răng miệng",
      "thể dục thể thao",
      "yoga và thiền",
      "sức khỏe đường ruột",
      "sức khỏe hô hấp",
      "kiểm tra sức khỏe định kỳ",
      "béo phì",
      "lối sống lành mạnh",
    ];